Added timestamp adapter
TUW-GEO/pytesmo pull request #268
Opened 2022-05-09 13:20 UTC by pstradio

Added a timestamp adapter for datasets that are read with an index in midnight UTC units and an additional field with the time offset. The adapter returns the original fields with the exact observation timestamp.

Applicable for instance to:

- SMOS L3
- SMAP L3
- C3S
- CCI

2022-05-09 13:35 UTC, pstradio commented on src/pytesmo/validation_framework/adapters.py
> +    time_units: str, optional. Default is "s".
Ah yes

2022-05-09 13:35 UTC, pstradio commented on src/pytesmo/validation_framework/adapters.py
> +    Class that adapts the (midnight) timestamp read with the generic read function
Yes that is why I put it in brackets..ok I'll update it

2022-05-09 13:43 UTC, pstradio commented on src/pytesmo/validation_framework/adapters.py
> +    Class that adapts the (midnight) timestamp read with the generic read function
ok I will update this

2022-05-09 13:46 UTC, pstradio commented on src/pytesmo/validation_framework/adapters.py
> +    Class that adapts the (midnight) timestamp read with the generic read function
But in that case why wouldn't that column be used in the reader directly?

2022-05-09 13:49 UTC, wpreimes commented on src/pytesmo/validation_framework/adapters.py
> +    Class that adapts the (midnight) timestamp read with the generic read function
I imagine the case when the time stamp was taken e.g from the filename, but when there is one or multiple variables in the file (based on some unit) that you would actually combine to get the exact time

2022-05-09 13:51 UTC, wpreimes commented on src/pytesmo/validation_framework/adapters.py
> +    Class that adapts the (midnight) timestamp read with the generic read function
in that case I think it would be easier to start from the given reference date (instead of the date in the index).

2022-05-12 11:40 UTC, pstradio commented
Coverage decreases for some reason, but the tests i have added are covering all the new functions

2022-05-12 13:05 UTC, wpreimes requested changes
Otherwise it's fine, please update the Changelog!

2022-05-12 13:05 UTC, wpreimes commented on src/pytesmo/validation_framework/adapters.py
> +        self.generic_time_field = generic_time_field
Maybe base_time would be a better name than generic_time?

2022-05-12 14:15 UTC, pstradio commented on src/pytesmo/validation_framework/adapters.py
> +    handle_invalid: str, optional. Default is 'return_original'
@wpreimes  Let me know if this makes sense for you; I believe it should be fine and flexible like this

2022-05-13 11:37 UTC, merged